class ANY:
    FAIL = 0xFF
    IDENTITY = 0x00


class ARRAY:
    COUNT = 0x10
    FILTER = 0x11
    GET_ARRAY = 0x13
    GET_BOOLEAN = 0x14
    GET_BYTES = 0x15
    GET_FLOAT = 0x16
    GET_INTEGER = 0x17
    GET_MAP = 0x18
    GET_STRING = 0x19
    MAP = 0x1A
    REDUCE = 0x1B
    SORT = 0x1D


class BOOLEAN:
    AS_STRING = 0x20
    NEGATE = 0x22


class BYTES:
    AS_STRING = 0x30
    HASH = 0x31


class FLOAT:
    ABSOLUTE = 0x50
    AS_STRING = 0x51
    CEILING = 0x52
    FLOOR = 0x54
    GREATER_THAN = 0x53
    LESS_THAN = 0x55
    MODULO = 0x56
    MULTIPLY = 0x57
    NEGATE = 0x58
    POWER = 0x59
    ROUND = 0x5B
    TRUNCATE = 0x5d


class INTEGER:
    ABSOLUTE = 0x40
    AS_FLOAT = 0x41
    AS_STRING = 0x42
    GREATER_THAN = 0x43
    LESS_THAN = 0x44
    MODULO = 0x46
    MULTIPLY = 0x47
    NEGATE = 0x48
    POWER = 0x49


class MAP:
    GET_ARRAY = 0x61
    GET_BOOLEAN = 0x62
    GET_BYTES = 0x63
    GET_FLOAT = 0x64
    GET_INTEGER = 0x65
    GET_MAP = 0x66
    GET_STRING = 0x67
    KEYS = 0x68
    VALUES_AS_ARRAY = 0x69


class STRING:
    AS_BOOLEAN = 0x70
    AS_FLOAT = 0x72
    AS_INTEGER = 0x73
    LENGTH = 0x74
    MATCH = 0x75
    PARSE_JSON_ARRAY = 0x76
    PARSE_JSON_MAP = 0x77
    TO_LOWER_CASE = 0x79
    TO_UPPER_CASE = 0x7A


class OP:
    ANY_FAIL = ANY.FAIL
    ANY_IDENTITY = ANY.IDENTITY
    ARRAY_COUNT = ARRAY.COUNT
    ARRAY_FILTER = ARRAY.FILTER
    ARRAY_GET_ARRAY = ARRAY.GET_ARRAY
    ARRAY_GET_BOOLEAN = ARRAY.GET_BOOLEAN
    ARRAY_GET_BYTES = ARRAY.GET_BYTES
    ARRAY_GET_FLOAT = ARRAY.GET_FLOAT
    ARRAY_GET_INTEGER = ARRAY.GET_INTEGER
    ARRAY_GET_MAP = ARRAY.GET_MAP
    ARRAY_GET_STRING = ARRAY.GET_STRING
    ARRAY_MAP = ARRAY.GET_ARRAY
    ARRAY_REDUCE = ARRAY.REDUCE
    ARRAY_SORT = ARRAY.SORT
    BOOLEAN_AS_STRING = BOOLEAN.AS_STRING
    BOOLEAN_NEGATE = BOOLEAN.NEGATE
    BYTES_AS_STRING = BYTES.AS_STRING
    BYTES_HASH = BYTES.HASH
    FLOAT_ABSOLUTE = FLOAT.ABSOLUTE
    FLOAT_AS_STRING = FLOAT.AS_STRING
    FLOAT_CEILING = FLOAT.CEILING
    FLOAT_FLOOR = FLOAT.FLOOR
    FLOAT_GREATER_THAN = FLOAT.GREATER_THAN
    FLOAT_LESS_THAN = FLOAT.LESS_THAN
    FLOAT_MODULO = FLOAT.MODULO
    FLOAT_MULTIPLY = FLOAT.MULTIPLY
    FLOAT_NEGATE = FLOAT.NEGATE
    FLOAT_POWER = FLOAT.POWER
    FLOAT_ROUND = FLOAT.ROUND
    FLOAT_TRUNCATE = FLOAT.TRUNCATE
    INTEGER_ASBOLUTE = INTEGER.ABSOLUTE
    INTEGER_AS_FLOAT = INTEGER.AS_FLOAT
    INTEGER_AS_STRING = INTEGER.AS_STRING
    INTEGER_GREATER_THAN = INTEGER.GREATER_THAN
    INTEGER_LESS_THAN = INTEGER.LESS_THAN
    INTEGER_MODULO = INTEGER.MODULO
    INTEGER_MULTIPLY = INTEGER.MULTIPLY
    INTEGER_NEGATE = INTEGER.NEGATE
    INTEGER_POWER = INTEGER.POWER
    MAP_GET_ARRAY = MAP.GET_ARRAY
    MAP_GET_BOOLEAN = MAP.GET_BOOLEAN
    MAP_GET_BYTES = MAP.GET_BYTES
    MAP_GET_FLOAT = MAP.GET_FLOAT
    MAP_GET_INTEGER = MAP.GET_INTEGER
    MAP_GET_MAP = MAP.GET_MAP
    MAP_GET_STRING = MAP.GET_STRING
    MAP_KEYS = MAP.KEYS
    MAP_VALUES_AS_ARRAY = MAP.VALUES_AS_ARRAY
    STRING_AS_BOOLEAN = STRING.AS_BOOLEAN
    STRING_AS_FLOAT = STRING.AS_FLOAT
    STRING_AS_INTEGER = STRING.AS_INTEGER
    STRING_LENGTH = STRING.LENGTH
    STRING_MATCH = STRING.MATCH
    STRING_PARSE_JSON_ARRAY = STRING.PARSE_JSON_ARRAY
    STRING_PARSE_JSON_MAP = STRING.PARSE_JSON_MAP
    STRING_TO_LOWER_CASE = STRING.TO_LOWER_CASE
    STRING_TO_UPPER_CASE = STRING.TO_UPPER_CASE


OP_STR = {
    OP.ANY_FAIL: 'Any.Fail',
    OP.ANY_IDENTITY: 'Any.Identity',
    OP.ARRAY_COUNT: 'Array.count',
    OP.ARRAY_GET_ARRAY: 'Array.getArray',
    OP.ARRAY_GET_BOOLEAN: 'Array.getBoolean',
    OP.ARRAY_GET_BYTES: 'Array.getBytes',
    OP.ARRAY_GET_INTEGER: 'Array.getInteger',
    OP.ARRAY_GET_MAP: 'Array.getMap',
    OP.ARRAY_GET_STRING: 'Array.getString',
    OP.BOOLEAN_AS_STRING: 'Boolean.asString',
    OP.BOOLEAN_NEGATE: 'Boolean.negate',
    OP.BYTES_AS_STRING: 'Bytes.asString',
    OP.BYTES_HASH: 'Bytes.hash',
    OP.FLOAT_ABSOLUTE: 'Float.absolute',
    OP.FLOAT_AS_STRING: 'Float.asString',
    OP.FLOAT_CEILING: 'Float.ceiling',
    OP.FLOAT_FLOOR: 'Float.floor',
    OP.FLOAT_GREATER_THAN: 'Float.greaterThan',
    OP.FLOAT_LESS_THAN: 'Float.lessThan',
    OP.FLOAT_MODULO: 'Float.modulo',
    OP.FLOAT_MULTIPLY: 'Float.multiply',
    OP.FLOAT_NEGATE: 'Float.negate',
    OP.FLOAT_POWER: 'Float.power',
    OP.FLOAT_ROUND: 'Float.round',
    OP.FLOAT_TRUNCATE: 'Float.truncate',
    OP.INTEGER_ASBOLUTE: 'Integer.absolute',
    OP.INTEGER_AS_FLOAT: 'Integer.asFloat',
    OP.INTEGER_AS_STRING: 'Integer.asString',
    OP.INTEGER_GREATER_THAN: 'Integer.greaterThan',
    OP.INTEGER_LESS_THAN: 'Integer.lessThan',
    OP.INTEGER_MODULO: 'Integer.modulo',
    OP.INTEGER_MULTIPLY: 'Integer.multiply',
    OP.INTEGER_NEGATE: 'Integer.negate',
    OP.INTEGER_POWER: 'Integer.power',
    OP.MAP_GET_ARRAY: 'Map.getArray',
    OP.MAP_GET_BOOLEAN: 'Map.getBoolean',
    OP.MAP_GET_BYTES: 'Map.getBytes',
    OP.MAP_GET_FLOAT: 'Map.getFloat',
    OP.MAP_GET_INTEGER: 'Map.getInteger',
    OP.MAP_GET_MAP: 'Map.getMap',
    OP.MAP_GET_STRING: 'Map.getString',
    OP.STRING_AS_BOOLEAN: 'String.asBoolean',
    OP.STRING_AS_FLOAT: 'String.asFloat',
    OP.STRING_AS_INTEGER: 'String.asInteger',
    OP.STRING_LENGTH: 'String.length',
    OP.STRING_MATCH: 'String.match',
    OP.STRING_PARSE_JSON_ARRAY: 'String.parseJSONArray',
    OP.STRING_PARSE_JSON_MAP: 'String.parseJSONMap',
    OP.STRING_TO_LOWER_CASE: 'String.toLowerCase',
    OP.STRING_TO_UPPER_CASE: 'String.toUpperCase',
}
